### ISSUE TITLE
GDAL 3.x series builds are timing out

### ISSUE THREAD

**Issue by rbreslow** [azavea/docker-openjdk-gdal#14]
For now, the 3.x series will have to be published locally. When time permits or it becomes a priority, #11 may resolve this issue.

**Comment by hectcastro** [comment]
As stated, I don't think this is the case any longer due to the resolution of https://github.com/azavea/docker-openjdk-gdal/issues/11. Does it make sense to close this and focus on https://github.com/azavea/docker-openjdk-gdal/issues/13?
