### ISSUE TITLE
Publish images for GDAL 2.4.0

### ISSUE THREAD

**Issue by jeancochrane** [azavea/docker-openjdk-gdal#2]
Create images with GDAL 2.4.0.

See:

* https://trac.osgeo.org/gdal/wiki/Release/2.4.0-News

**Comment by hectcastro** [comment]
Just a note here to consider dropping the patch version from the container image name used to `2.4` vs. `2.4.0`.

**Comment by pomadchin** [comment]
A note that in GDAL 2.3.2+ (I'm not sure starting from what version they introduced a fix; it definitely works for 2.4) we don't need [these](https://github.com/azavea/docker-openjdk-gdal/blob/master/Dockerfile-slim.template#L62-L63) lines anymore as they fixed builds. 

[Example diff](https://github.com/geotrellis/geotrellis-gdal/commit/e8c049cec46b0426bfc45d70209c5ac80d887dca#diff-3254677a7917c6c01f55212f86c57fbf)
